apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: my-template
  title: My Service
  description: Create a Golang repo with this template built by members of the Go community
  tags:
    - java
spec:
  owner: web@example.com
  templater: cookiecutter
  type: service
  path: "."
  schema:
    required:
      - nome
    
