[package]
name = "${{values.name}}"
version = "0.1.0"
edition = "${{values.rust_edition}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
